version: '3.5'

services:
  sectorserver:
    image: dulce/sector-server:dev
    build:
      context: ../../
      dockerfile: Docker/Dev/Server/Dockerfile

  sectorclient:
    image: dulce/sector-client:dev
    build:
      context: ../../
      dockerfile: Docker/Dev/Client/Dockerfile
