version: '3.5'

services:
  sectorserver:
    image: dulce/sector-server:dev
    build:
      context: ../../
      dockerfile: Environments/Development/Server/Dockerfile

  sectorclient:
    image: dulce/sector-client:dev
    build:
      context: ../../
      dockerfile: Environments/Development/Client/Dockerfile
