version: '3.5'

services:
  scheduleserver:
    image: dulce/schedule-server:prod
    build:
      context: ../../
      dockerfile: Environments/Production/Server/Dockerfile

  scheduleclient:
    image: dulce/schedule-client:prod
    build:
      context: ../../
      dockerfile: Environments/Production/Client/Dockerfile
